import { parseShots, checkShots, blockingProblems } from '../studio/ask/storyboard';
import type { ShotTarget } from '../studio/ask/storyboard';

const CLAUDE_OUTPUT = `Thought for 2m 30s
Thought for 2m 30s
{
"cast": [
{
"name": "GameCourt 2",
"role": "hero product",
"look": "a white engineered-mesh adidas GameCourt 2 tennis shoe with a deep purple-grey padded heel collar and tongue, three black diagonal side stripes, a small gold foil 'GAMECOURT 2' wordmark on the outer heel, a white EVA midsole with a grey gradient, a white rubber herringbone outsole, and flat purple-grey laces, exactly as shown on the character sheet, with no scuffing or wear and no change to its colour, stripe count, or wordmark from shot to shot"
}
],
"world": "a saturated cobalt-blue hard-court tennis surface with crisp white boundary lines and visible woven court texture, open-air daylight consistent with late-afternoon sun, a strung tennis racquet and a fuzzed yellow tennis ball entering the frame only at its edges, and with no other shoes or people entering fully into frame anywhere in the scene",
"look": "photorealistic 8K live-action cinematography with natural cinematic lighting, rich depth of field, and authentic textures, captured on a full-frame cinema camera with shallow depth of field, natural late-afternoon sunlight acting as the key light raking low from camera-left and casting long hard-edged shadows, a subtle warm rim light along the far edge, high micro-contrast on the mesh and rubber textures, true-to-life colour with the blue court kept saturated and the shoe kept neutral white, premium sportswear commercial grade with no CGI gloss, no 3D render look, no cartoon styling, no distorted anatomy, no plastic skin, no on-screen text, no captions, no subtitles, no watermark, no stickers, no fake app interface, and no logos overlaid on the picture",
"story": "A single adidas GameCourt 2 tennis shoe is revealed in tactile macro texture, rotated and pushed into hero focus on an empty golden-hour court, then the camera pulls back into the kinetic energy of live match play, ending on a wide court frame with open negative space for a title card.",
"anchor": "Every prompt carries the identical shoe description (white mesh, purple-grey heel collar and tongue, three black diagonal stripes, gold foil 'GAMECOURT 2' wordmark, grey-gradient EVA midsole, white herringbone outsole, purple-grey laces, no scuffing, no colour/stripe/wordmark change), the identical cobalt-blue court world with racquet and ball only entering at the edges and no other shoes or people entering fully into frame, an ARRI Alexa 35 full-frame cinema camera body throughout, and the same key light raking low from camera-left casting long hard-edged shadows with a subtle warm rim light.",
"shots": [
{
"n": 1,
"title": "Hero still",
"cast": ["GameCourt 2"],
"prompt": "A clear, evenly lit reference photograph of a white engineered-mesh adidas GameCourt 2 tennis shoe with a deep purple-grey padded heel collar and tongue, three black diagonal side stripes, a small gold foil 'GAMECOURT 2' wordmark on the outer heel, a white EVA midsole with a grey gradient, a white rubber herringbone outsole, and flat purple-grey laces, exactly as shown on the character sheet, with no scuffing or wear and no change to its colour, stripe count, or wordmark from shot to shot, standing upright and fully visible at a three-quarter hero angle on a saturated cobalt-blue hard-court tennis surface with crisp white boundary lines and visible woven court texture, open-air daylight consistent with late-afternoon sun, a strung tennis racquet and a fuzzed yellow tennis ball entering the frame only at its edges, and with no other shoes or people entering fully into frame anywhere in the scene. Photorealistic 8K live-action cinematography with natural cinematic lighting, rich depth of field, and authentic textures, captured on a full-frame cinema camera with shallow depth of field, natural late-afternoon sunlight acting as the key light raking low from camera-left and casting long hard-edged shadows, a subtle warm rim light along the far edge, high micro-contrast on the mesh and rubber textures, true-to-life colour with the blue court kept saturated and the shoe kept neutral white, premium sportswear commercial grade with no CGI gloss, no 3D render look, no cartoon styling, no distorted anatomy, no plastic skin, no on-screen text, no captions, no subtitles, no watermark, no stickers, no fake app interface, and no logos overlaid on the picture. Photographed with an ARRI Alexa 35 full-frame cinema camera fitted with a Zeiss Supreme Prime 40mm lens at eye level, camera locked off and perfectly static, with a soft camera-right fill balancing the raking camera-left key light so every panel of the shoe stays legible with nothing cropped or hidden — the toe, the gold foil wordmark, the three diagonal side stripes, the padded heel collar, and the full herringbone outsole all clearly readable — and the shoe composed in the lower two-thirds of the vertical frame, leaving open negative space above for a future title card."
},
{
"n": 2,
"title": "Macro sole close-up",
"cast": ["GameCourt 2"],
"prompt": "Opening on an extreme macro close-up of the white rubber herringbone outsole and the grey-gradient white EVA midsole edge of a white engineered-mesh adidas GameCourt 2 tennis shoe with a deep purple-grey padded heel collar and tongue, three black diagonal side stripes, a small gold foil 'GAMECOURT 2' wordmark on the outer heel, flat purple-grey laces, exactly as shown on the character sheet, with no scuffing or wear and no change to its colour, stripe count, or wordmark from shot to shot, resting motionless at the start of the shot on a saturated cobalt-blue hard-court tennis surface with crisp white boundary lines and visible woven court texture, open-air daylight consistent with late-afternoon sun, a strung tennis racquet and a fuzzed yellow tennis ball entering the frame only at its edges, and with no other shoes or people entering fully into frame anywhere in the scene, the herringbone tread pattern sharp in focus filling most of the vertical frame with the blurred blue court texture beyond it. Photorealistic 8K live-action cinematography with natural cinematic lighting, rich depth of field, and authentic textures, captured on a full-frame cinema camera with shallow depth of field, natural late-afternoon sunlight acting as the key light raking low from camera-left and casting long hard-edged shadows, a subtle warm rim light along the far edge, high micro-contrast on the mesh and rubber textures, true-to-life colour with the blue court kept saturated and the shoe kept neutral white, premium sportswear commercial grade with no CGI gloss, no 3D render look, no cartoon styling, no distorted anatomy, no plastic skin, no on-screen text, no captions, no subtitles, no watermark, no stickers, no fake app interface, and no logos overlaid on the picture. Shot on an ARRI Alexa 35 full-frame cinema camera fitted with a Laowa 24mm probe macro lens for true macro magnification, the camera performing a slow macro dolly crawl low across the court surface from right to left along the length of the outsole; as the camera crawls, the shoe presses down firmly into the court in a single stamping motion, the herringbone tread flexing and gripping the woven surface as a fine puff of court dust kicks up at the point of contact and settles just as the crawl completes. Ambient noise: open-air court ambience with a faint breeze and distant stadium hum. SFX: a sharp rubber squeak as the outsole grips the court, followed by a soft puff of dust settling."
},
{
"n": 3,
"title": "Rotating push-in",
"cast": ["GameCourt 2"],
"prompt": "A white engineered-mesh adidas GameCourt 2 tennis shoe with a deep purple-grey padded heel collar and tongue, three black diagonal side stripes, a small gold foil 'GAMECOURT 2' wordmark on the outer heel, a white EVA midsole with a grey gradient, a white rubber herringbone outsole, and flat purple-grey laces, exactly as shown on the character sheet, with no scuffing or wear and no change to its colour, stripe count, or wordmark from shot to shot, stands upright and fully assembled at the center of a saturated cobalt-blue hard-court tennis surface with crisp white boundary lines and visible woven court texture, open-air daylight consistent with late-afternoon sun, a strung tennis racquet and a fuzzed yellow tennis ball entering the frame only at its edges, and with no other shoes or people entering fully into frame anywhere in the scene, planted on its outsole at the court's baseline with the full shoe visible from toe to heel collar at the start of the shot. Photorealistic 8K live-action cinematography with natural cinematic lighting, rich depth of field, and authentic textures, captured on a full-frame cinema camera with shallow depth of field, natural late-afternoon sunlight acting as the key light raking low from camera-left and casting long hard-edged shadows, a subtle warm rim light along the far edge, high micro-contrast on the mesh and rubber textures, true-to-life colour with the blue court kept saturated and the shoe kept neutral white, premium sportswear commercial grade with no CGI gloss, no 3D render look, no cartoon styling, no distorted anatomy, no plastic skin, no on-screen text, no captions, no subtitles, no watermark, no stickers, no fake app interface, and no logos overlaid on the picture. Shot on an ARRI Alexa 35 full-frame cinema camera fitted with a Zeiss Supreme Prime 50mm lens mounted on a motion-control robotic arm, the camera performing a rotating push-in — arcing thirty degrees around the shoe from camera-right toward camera-left while simultaneously moving closer — as the low raking sunlight sweeps across the gold foil wordmark and the three diagonal side stripes, causing the mesh texture and stripe edges to flare briefly with rim light before the move settles into a tight three-quarter framing that fills most of the vertical frame, with no change to the shoe's colour, stripe count, or wordmark at any point during the motion. Ambient noise: open-air court ambience with a faint breeze and distant stadium hum. SFX: a low mechanical whir of the camera rig arcing through the air and a soft whoosh of moving air across the mesh upper."
},
{
"n": 4,
"title": "Court reveal pull-back",
"cast": ["GameCourt 2"],
"prompt": "Continuing directly from the tight three-quarter hero framing already reached in the previous motion, a white engineered-mesh adidas GameCourt 2 tennis shoe with a deep purple-grey padded heel collar and tongue, three black diagonal side stripes, a small gold foil 'GAMECOURT 2' wordmark on the outer heel, a white EVA midsole with a grey gradient, a white rubber herringbone outsole, and flat purple-grey laces, exactly as shown on the character sheet, with no scuffing or wear and no change to its colour, stripe count, or wordmark from shot to shot, fills most of the vertical frame at the center of a saturated cobalt-blue hard-court tennis surface with crisp white boundary lines and visible woven court texture, open-air daylight consistent with late-afternoon sun, a strung tennis racquet and a fuzzed yellow tennis ball entering the frame only at its edges, and with no other shoes or people entering fully into frame anywhere in the scene, the low sunlight still raking across the gold foil wordmark and the three diagonal side stripes exactly as it was a moment before. Photorealistic 8K live-action cinematography with natural cinematic lighting, rich depth of field, and authentic textures, captured on a full-frame cinema camera with shallow depth of field, natural late-afternoon sunlight acting as the key light raking low from camera-left and casting long hard-edged shadows, a subtle warm rim light along the far edge, high micro-contrast on the mesh and rubber textures, true-to-life colour with the blue court kept saturated and the shoe kept neutral white, premium sportswear commercial grade with no CGI gloss, no 3D render look, no cartoon styling, no distorted anatomy, no plastic skin, no on-screen text, no captions, no subtitles, no watermark, no stickers, no fake app interface, and no logos overlaid on the picture. Shot on the same ARRI Alexa 35 full-frame cinema camera, now fitted with a Zeiss Supreme Prime 25mm lens mounted on a technocrane, the camera performing a rapid pull-back straight up and away from the shoe along the crane arm, opening the frame in one continuous move from the tight hero shot out to a full view of the entire court; as the camera rises and retreats, the shoe stays grounded and sharp in the foreground while the rest of the cobalt-blue court opens up behind it, the fuzzed yellow tennis ball streaking across the far half of the court and the strung racquet swinging in only at the very edge of frame, with distant figures visible only as motion-blurred silhouettes at the far baseline and never entering fully into the frame, and with no change to the shoe's colour, stripe count, or wordmark throughout the move. Ambient noise: open-air stadium ambience swelling with distant crowd murmur and wind across the court. SFX: a rising whoosh of the crane rig pulling back, a sharp pop of a racquet striking the ball in the distance, and a faint rubber squeak as the shoe stays planted."
}
]
}`;

describe('Claude Story Output Parser', () => {
  it('parses shots cleanly despite Thought prefix', () => {
    const parsed = parseShots(CLAUDE_OUTPUT);
    expect(parsed.problem).toBeUndefined();
    expect(parsed.shots).toHaveLength(4);
    expect(parsed.cast).toHaveLength(1);
    expect(parsed.cast![0].name).toBe('GameCourt 2');
  });

  it('checks shots against targets', () => {
    const parsed = parseShots(CLAUDE_OUTPUT);
    const targets: ShotTarget[] = [
      { id: '1', label: 'Hero still', role: 'reference', media: 'image', platform: 'grok', aspectRatio: '9:16' },
      { id: '2', label: 'Macro sole close-up', role: 'shot', media: 'video', platform: 'flow', aspectRatio: '9:16', duration: '4s' },
      { id: '3', label: 'Rotating push-in', role: 'shot', media: 'video', platform: 'flow', aspectRatio: '9:16', duration: '6s' },
      { id: '4', label: 'Court reveal pull-back', role: 'continuation', media: 'video', platform: 'flow', aspectRatio: '9:16', duration: '6s', continues: 'Rotating push-in' },
    ];
    const problems = checkShots(parsed.shots, targets, parsed.anchor, parsed.cast);
    console.log('Problems found:', problems);
    const blocking = blockingProblems(problems);
    console.log('Blocking problems:', blocking);
  });
});
