# Generated by Django 5.1.15 on 2026-05-10 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(help_text='Original filename of the video.', max_length=255)),
                ('video_concept', models.TextField(blank=True, help_text='Overall concept of the video.', null=True)),
                ('voiceover_text', models.TextField(blank=True, help_text='Extracted voiceover script.', null=True)),
                ('character_sheets', models.JSONField(blank=True, default=list, help_text='List of character designs.')),
                ('shots', models.JSONField(blank=True, default=list, help_text='Timeline of shots and prompts.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='The user who saved this extraction.', on_delete=django.db.models.deletion.CASCADE, related_name='saved_extractions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Extraction',
                'verbose_name_plural': 'Saved Extractions',
                'ordering': ['-created_at'],
            },
        ),
    ]
