# Generated by Django 5.1.15 on 2026-08-02 10:47

from django.db import migrations, models


def publish_existing(apps, schema_editor):
    """Keep rows that are already public, public.

    /prompts and the sitemap are built from this endpoint and are indexed, so
    defaulting everything to private would empty a live section of the site and
    drop URLs Google already knows about. New extractions are private from here
    on; deciding whether to retroactively unpublish these is a separate call —
    `manage.py unpublish_extractions` does it in one step.
    """
    apps.get_model('extractions', 'SavedExtraction').objects.update(is_public=True)


def unpublish_all(apps, schema_editor):
    apps.get_model('extractions', 'SavedExtraction').objects.update(is_public=False)


class Migration(migrations.Migration):

    dependencies = [
        ('extractions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedextraction',
            name='is_public',
            field=models.BooleanField(db_index=True, default=False, help_text='Show this extraction in the public prompt gallery.'),
        ),
        migrations.RunPython(publish_existing, unpublish_all),
    ]
