"""Admin for published template bundles — including publishing itself.

Publishing happens here rather than through a shared secret on purpose.

The alternative was a static token: generated by somebody, pasted into Railway,
pasted again into a shell. Every one of those steps is a place a long-lived
credential gets copied into a log, a screenshot or a chat window — and it
guards an endpoint that can replace the template bundle for every user at once.

Uploading in the admin needs no new secret at all. You are already
authenticated, the session is short-lived, Django checks staff status and CSRF
for us, and nothing sensitive exists outside the browser.

The token endpoint in views.py still exists, for CI later. Leaving
TEMPLATE_PUBLISH_TOKEN unset — the default — disables it entirely.
"""

import json

from django import forms
from django.contrib import admin, messages
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import path, reverse
from unfold.admin import ModelAdmin

from .models import TemplateBundle


class BundleUploadForm(forms.Form):
    """The templates.json produced by `npm run templates:export`."""

    file = forms.FileField(
        label="templates.json",
        help_text=(
            "Produced by 'npm run templates:export' in the studio-extension "
            "folder. It has already been validated there."
        ),
    )
    note = forms.CharField(
        max_length=500,
        required=False,
        label="What changed",
        help_text="Optional. Shows in the list, so a bad publish is easy to find and roll back.",
    )


@admin.register(TemplateBundle)
class TemplateBundleAdmin(ModelAdmin):
    """Read-mostly, plus the upload button.

    The one thing worth doing by hand on an existing row is unticking
    `is_active`. That rolls back to the previous bundle immediately, without
    needing whatever machine published the bad one.
    """

    list_display = ("published_at", "template_count", "schema_version", "is_active", "published_by", "note")
    list_filter = ("is_active", "schema_version")
    readonly_fields = ("etag", "published_at", "schema_version", "template_count")
    search_fields = ("note", "published_by")
    change_list_template = "admin/workflows/templatebundle/change_list.html"

    def get_urls(self):
        return [
            path(
                "publish/",
                self.admin_site.admin_view(self.publish_view),
                name="workflows_templatebundle_publish",
            ),
            *super().get_urls(),
        ]

    def publish_view(self, request):
        """Upload a bundle and make it the active one."""
        if request.method == "POST":
            form = BundleUploadForm(request.POST, request.FILES)
            if form.is_valid():
                try:
                    payload = json.load(form.cleaned_data["file"])
                except (json.JSONDecodeError, UnicodeDecodeError) as exc:
                    messages.error(request, f"That file is not valid JSON: {exc}")
                    return HttpResponseRedirect(request.path)

                problem = _shape_problem(payload)
                if problem:
                    messages.error(request, problem)
                    return HttpResponseRedirect(request.path)

                previous = TemplateBundle.current()
                bundle = TemplateBundle(
                    payload=payload,
                    published_by=request.user.get_username(),
                    note=form.cleaned_data["note"],
                )
                bundle.save()

                if previous and previous.etag == bundle.etag:
                    # Identical content. Keeping the older row active leaves its
                    # ETag stable, so every extension's revalidation stays a 304
                    # instead of re-downloading a bundle it already holds.
                    bundle.is_active = False
                    bundle.save(update_fields=["is_active"])
                    messages.info(
                        request,
                        f"No change — the {previous.template_count} templates already published are identical.",
                    )
                else:
                    TemplateBundle.objects.exclude(pk=bundle.pk).filter(is_active=True).update(is_active=False)
                    messages.success(
                        request,
                        f"Published {bundle.template_count} templates. "
                        "Extensions pick them up the next time Studio opens.",
                    )
                return HttpResponseRedirect(reverse("admin:workflows_templatebundle_changelist"))
        else:
            form = BundleUploadForm()

        return render(
            request,
            "admin/workflows/publish.html",
            {
                **self.admin_site.each_context(request),
                "form": form,
                "title": "Publish templates",
                "current": TemplateBundle.current(),
                "opts": self.model._meta,
            },
        )


def _shape_problem(payload) -> str:
    """Reject a payload that would break galleries, in plain language.

    The extension's publish script has already run the real validation, next to
    the source, where a failure is a readable list beside the template that
    caused it. These are the checks that matter on this side of the wire: that
    the file is the right shape, and that it is not empty.
    """
    if not isinstance(payload, dict) or not isinstance(payload.get("templates"), list):
        return 'Expected a file containing {"schemaVersion": 1, "templates": [...]}.'

    templates = payload["templates"]
    if not templates:
        # An empty publish blanks every gallery on the next fetch. To withdraw
        # everything, untick is_active on the current bundle — that is
        # reversible and obviously deliberate.
        return "That file has no templates in it. Refusing to publish an empty bundle."

    broken = [
        t.get("id", "(no id)")
        for t in templates
        if not t.get("id") or not isinstance(t.get("nodes"), list) or not isinstance(t.get("edges"), list)
    ]
    if broken:
        return f"These templates are missing id, nodes or edges: {', '.join(broken[:5])}"
    return ""


# ── Community templates ──
# A moderation queue, not an editor. The payload is a node graph authored in
# the extension; the only decisions worth making here are publish, reject, and
# what the gallery calls it.
from .community import CommunityTemplate, TemplateLike  # noqa: E402


@admin.register(CommunityTemplate)
class CommunityTemplateAdmin(ModelAdmin):
    list_display = ("name", "author_name", "status", "node_count", "like_count", "install_count", "created_at")
    list_filter = ("status", "category")
    search_fields = ("name", "description", "author_name")
    readonly_fields = ("node_count", "like_count", "install_count", "created_at", "updated_at", "payload")
    actions = ("approve", "reject")
    # Newest pending first: the queue is the job, the leaderboard is not.
    ordering = ("status", "-created_at")

    @admin.action(description="Publish — visible to every user")
    def approve(self, request, queryset):
        n = queryset.update(status=CommunityTemplate.Status.PUBLISHED)
        messages.success(request, f"Published {n} template(s). They appear in the gallery on the next refresh.")

    @admin.action(description="Reject — hide from the gallery")
    def reject(self, request, queryset):
        n = queryset.update(status=CommunityTemplate.Status.REJECTED)
        messages.info(request, f"Rejected {n} template(s).")


@admin.register(TemplateLike)
class TemplateLikeAdmin(ModelAdmin):
    """Here to make the count auditable — a like_count that disagrees with
    these rows is the bug worth being able to see."""

    list_display = ("template", "user", "created_at")
    search_fields = ("template__name",)
    readonly_fields = ("template", "user", "created_at")
