# Generated by Django 5.1.15 on 2026-05-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pro_expires_at',
            field=models.DateTimeField(blank=True, help_text='If set, Pro access expires at this time (e.g. review reward)', null=True),
        ),
    ]
