# Generated by Django 5.1.15 on 2026-05-13 19:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRewardClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When admin approved or rejected', null=True)),
                ('pro_granted_until', models.DateTimeField(blank=True, help_text='Pro access expires at this time', null=True)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_claim', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'review reward claim',
                'verbose_name_plural': 'review reward claims',
            },
        ),
    ]
