# Generated by Django 5.1.15 on 2026-05-14 09:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSequenceSubscriber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('action_taken', models.BooleanField(default=False, help_text='True when the user clicked the CTA or purchased.')),
                ('emails_sent', models.PositiveSmallIntegerField(default=0, help_text='Number of emails sent so far (0–3).')),
                ('last_email_at', models.DateTimeField(blank=True, help_text='Timestamp of the most recent email in the sequence.', null=True)),
                ('sequence_completed', models.BooleanField(default=False, help_text='True when all 3 emails have been sent or user took action.')),
                ('tracking_token', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Unique token embedded in CTA links for click tracking.', unique=True)),
                ('source', models.CharField(choices=[('extension', 'Chrome Extension'), ('website', 'Website'), ('manual', 'Manual / Admin')], default='extension', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email Subscriber',
                'verbose_name_plural': 'Email Subscribers',
                'ordering': ['-created_at'],
            },
        ),
    ]
