# Generated by Django 5.1.15 on 2026-09-09 21:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usage', '0009_clipping_usage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_id', models.CharField(max_length=128, unique=True)),
                ('mode', models.CharField(blank=True, default='', max_length=32)),
                ('held', models.PositiveIntegerField(default=0, help_text='Still claimed and not yet spent.')),
                ('committed', models.PositiveIntegerField(default=0, help_text='Spent — one per prompt Flow actually received.')),
                ('held_text', models.PositiveIntegerField(default=0)),
                ('held_full', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'prompt reservation',
                'verbose_name_plural': 'prompt reservations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='usageevent',
            name='media_id',
            field=models.CharField(blank=True, default=None, help_text="Flow's own id for the generation this prompt produced.", max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='prompt_index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usageevent',
            name='queue_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='usageevent',
            name='event_type',
            field=models.CharField(choices=[('consume_prompt', 'Consume Prompt'), ('queue_started', 'Queue Started'), ('queue_finished', 'Queue Finished'), ('prompt_failed', 'Prompt Failed'), ('download_completed', 'Download Completed'), ('run_aborted', 'Run Aborted'), ('reward_granted', 'Reward Granted'), ('queue_run_lite', 'Queue Run (Lite)'), ('queue_run_flow', 'Queue Run (Flow)'), ('queue_run_full', 'Queue Run (Full)'), ('clipping_job_started', 'Clipping Job Started'), ('prompt_submitted', 'Prompt Submitted to Flow')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['user', 'event_type', 'created_at'], name='usageevent_user_type_at'),
        ),
        migrations.AddIndex(
            model_name='usageevent',
            index=models.Index(fields=['queue_id', 'prompt_index'], name='usageevent_queue_index'),
        ),
        migrations.AddField(
            model_name='promptreservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='promptreservation',
            index=models.Index(fields=['user', 'released_at', 'expires_at'], name='reservation_user_open'),
        ),
    ]
