# Generated by Django 5.1.15 on 2026-09-29 22:32
# ruff: noqa: RUF012

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MotionMembership",
            fields=[
                (
                    "membership_id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("product_id", models.CharField(max_length=128)),
                ("plan_id", models.CharField(max_length=128)),
                ("email", models.EmailField(db_index=True, max_length=254)),
                ("active", models.BooleanField(default=False)),
                ("state_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="MotionWebhookReceipt",
            fields=[
                (
                    "event_id",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("event_type", models.CharField(max_length=100)),
                ("payload_hash", models.CharField(max_length=64)),
                ("disposition", models.CharField(max_length=40)),
                ("membership_id", models.CharField(blank=True, max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MotionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("job_id", models.UUIDField()),
                ("fingerprint", models.CharField(max_length=64)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user", "date"], name="motion_user_date")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "job_id"), name="motion_unique_user_job"
                    )
                ],
            },
        ),
    ]
